### PR TITLE
List of domains to test

### PR DESCRIPTION
**Pull request by spirillen**
My submission is to be understood as

1. Contributors, The list of users that have reached the list https://pyfunceble.readthedocs.io/en/dev/contributors.html
1. The list of domains for those who have reached https://pyfunceble.readthedocs.io/en/dev/special-thanks.html
1. Harmless, This is intended to be domains, that do not show any ads, do any tracking or requires any third party resources, but that list is hard to fill...
1. Doomed to fail, is a list of domains, that always should make it into the `INACTIVE` list
1. IDNA/punycode/sunrise domain
1. Controversial, is the list of domains that is widely used by user, knowingly or not, and for some lists would be blocked

The thought behind this list is among other within a feature request, where `--ci --debug` would replace `--autosave-minutes x` and `-f`or `-uf` with this, list to run at least twice to have PyFunceble execute `--commit-autosave-message` and `--cmd-before-end`.

This is useful for two reasons:

1. Why is my CI script failing, Check PyFunceble workflow
1. Debug any PyFunceble errors in workflow.

This list May never exceed two runs and should be able to stays inside the log length on any CI. See this https://travis-ci.com/Import-External-Sources/pornhosts/builds/146193907#L18098 which leads to a `--autosave-minutes x` of 1 minutes.

A couple of users for whom I could not find there website:
@dnmTX, @hawkeye116477, @jawz101, @kowith337, @Odyseus, @opav, @ybreza, @sjhgvr, @xxcriticxx, @SMed79 and @ZeroDot1 hxxp://`bit.ly/cBWeb`

### CODE REVIEW

**Comment by spirillen** [comment]
@hawkeye116477 why the :confused: face?

**Comment by smed79** [comment]
> why the :confused: face?

@spirillen This is not the right place for the submitted pull request.

@funilrys should review the repo permissions.

**Comment by kowith337** [comment]
Maybe you can ask as issues instead, in order to submit your lists to test with.

**Comment by spirillen** [comment]
> This is not the right place for the submitted pull request.

Where would you put it them @smed79

**Pull request merged**
